### ISSUE TITLE
Incorrect Documentation Regarding Output

### ISSUE THREAD

**Issue by jjm340** [amochkin/action-javascript#1]
```
- name: Execute Javascript
  uses: amochkin/action-javascript@v1
  id: <step_id>
  with:
    js: |
      output("output_1", "Hello World!")
- name: Print output
  run: echo ${{ steps.<step_id>.outputs.output_1 }}
```
This is in the docs; however, actually using this revealed that the `output()` function arguments should be switched:
`output("Hello World!", "output_1")`
